# Generated by Django 4.2.16 on 2025-01-23 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Authentications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(max_length=255, unique=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='videos/%y/%m/%d')),
                ('video_status', models.CharField(choices=[('approved', 'approved'), ('rejected', 'rejected'), ('previous_works', 'previous_works')], max_length=50, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='Authentications.userinfos')),
            ],
        ),
        migrations.CreateModel(
            name='VideoOrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unable_to_disapprove_creator', models.BooleanField(default=False)),
                ('project_name', models.CharField(max_length=60, null=True)),
                ('product_name', models.CharField(max_length=60, null=True)),
                ('product_description', models.CharField(max_length=500, null=True)),
                ('product_link', models.CharField(max_length=60, null=True)),
                ('product_img', models.ImageField(null=True, upload_to='photos/orders/product_img/%y/%m/%d')),
                ('video_duration', models.IntegerField(null=True)),
                ('video_size', models.CharField(max_length=60, null=True)),
                ('video_type', models.CharField(max_length=60, null=True)),
                ('num_of_videos', models.IntegerField(null=True)),
                ('additional_notes', models.CharField(max_length=2000, null=True)),
                ('video_price', models.IntegerField(null=True)),
                ('brand_name', models.CharField(max_length=60, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('creators_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('stripe_charge_id', models.CharField(max_length=100, null=True)),
                ('last4', models.CharField(max_length=4, null=True)),
                ('card_type', models.CharField(max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_status', models.CharField(choices=[('pending_creator_selecting', 'pending_creator_selecting'), ('pending_approval', 'pending_approval'), ('pending_creator_approval', 'pending_creator_approval'), ('completed', 'completed'), ('processing', 'processing'), ('cancelled', 'cancelled')], default='pending_creator_selecting', max_length=50)),
                ('applied_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Authentications.userinfos')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comapny_orders', to='Authentications.companydata')),
                ('selecting_creators', models.ManyToManyField(related_name='creators', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('videos', models.ManyToManyField(related_name='orders', to='brands.video')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentTrackingNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_num', models.CharField(max_length=200, null=True)),
                ('shipping_carrier', models.CharField(max_length=100, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_nums', to='brands.videoorderdetails')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_holder_name', models.CharField(max_length=255, null=True)),
                ('stripe_payment_method_id', models.CharField(max_length=255)),
                ('card_type', models.CharField(max_length=255)),
                ('last4', models.CharField(max_length=4)),
                ('exp_month', models.IntegerField(null=True)),
                ('exp_year', models.IntegerField(null=True)),
                ('default', models.BooleanField(default=False)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='brands.customer')),
            ],
        ),
    ]
