# Generated by Django 4.2.16 on 2025-01-23 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile', models.ImageField(default='default_photos/spotfay_pro_com.png', upload_to='photos/users_profile_images/%y/%m/%d')),
                ('country', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('postalcode', models.IntegerField(null=True)),
                ('phonenum', models.IntegerField(null=True)),
                ('birthdate', models.DateField(max_length=100, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=100, null=True)),
                ('userinfo', models.CharField(max_length=20000, null=True)),
                ('insta_account', models.CharField(max_length=2000, null=True)),
                ('tiktok_account', models.CharField(max_length=2000, null=True)),
                ('telegram_account', models.CharField(max_length=2000, null=True)),
                ('usertype', models.CharField(choices=[('content creator', 'Content Creator'), ('brand owner', 'Brand Owner')], default='brand owner', max_length=50)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userinfos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150, null=True)),
                ('company_activity', models.CharField(max_length=150, null=True)),
                ('company_country', models.CharField(max_length=150, null=True)),
                ('company_logo', models.ImageField(default='default_photos/spotfay_pro_com.png', upload_to='photos/companylogo/%y/%m/%d')),
                ('company_weblink', models.CharField(max_length=150, null=True)),
                ('company_socialmedia_account', models.CharField(max_length=150, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companydata', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
